cask_args appdir: "/Applications"

tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"

brew "mas"
brew "syncthing"

cask "alfred"
cask "appcleaner"
cask "deepl"
cask "discord"
cask "docker"
cask "dropbox"
cask "evernote"
cask "firefox"
cask "font-menlo-for-powerline"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-drive"
cask "hazel"
cask "intellij-idea-ce"
cask "iterm2"
cask "keycastr"
cask "macvim"
cask "omnifocus"
cask "omnigraffle"
cask "omnioutliner"
cask "pycharm-ce"
cask "resilio-sync"
cask "sourcetree"
cask "syncthing"
cask "vlc"
cask "zoom"
